language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro BITS=32
    - LISP=sbcl
    - LISP=sbcl32 BITS=32
    - LISP=ccl
    - LISP=ccl32 BITS=32
    - LISP=clisp
    - LISP=clisp32 BITS=32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    - env: LISP=cmucl
    # Fails when using cl-ssl
    - env: LISP=sbcl32
    - env: LISP=ccl32
    - env: LISP=clisp32
    - env: LISP=clisp
    # Fails for unknown reasons
    - env: LISP=allegro
    - env: LISP=ecl

# Install cl-travis
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - if [ $BITS = 32 ]; then sudo apt-get install libc6-dev-i386; fi

script:
  - cl -e '(ql:quickload :cl-scryfall/tests)
           (unless (cl-scryfall-tests:do-tests)
             (uiop:quit 1))'
