language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=ccl


matrix:
  allow_failures:
    - env: LISP=allegro


before_install:
    # Allegro needs the 32 bit libraries to compile
  - if [ $LISP = allegro ]; then sudo apt-get install libc6-dev-i386 && sudo apt-get install libssl-dev; fi

# Install cl-travis
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - cl -e '(ql:quickload :cl-scryfall/tests)
           (unless (cl-scryfall-tests:do-tests)
             (uiop:quit 1))'
