;;;; package.lisp

(defpackage #:cl-scryfall
  (:use #:cl #:asdf)
  (:export
   #:card-arena_id
   #:card-id
   #:card-lang
   #:card-mtgo_id
   #:card-mtgo_foil_id
   #:card-multiverse_ids
   #:card-object
   #:card-oracle_id
   #:card-prints_search_uri
   #:card-rulings_uri
   #:card-scryfall_uri
   #:card-uri
   #:card-all_parts
   #:card-card_faces
   #:card-cmc
   #:card-colors
   #:card-color_identity
   #:card-edhrec_rank
   #:card-foil
   #:card-hand_modifier
   #:card-layout
   #:card-legalities
   #:card-life_modifier
   #:card-loyalty
   #:card-mana_cost
   #:card-name
   #:card-nonfoil
   #:card-oracle_text
   #:card-oversized
   #:card-power
   #:card-reserved
   #:card-toughness
   #:card-type_line
   #:card-artist
   #:card-border_color
   #:card-collector_number
   #:card-colorshifted
   #:card-digital
   #:card-eur
   #:card-flavor_text
   #:card-frame
   #:card-full_art
   #:card-futureshifted
   #:card-highres_image
   #:card-illustration_id
   #:card-image_uris
   #:card-printed_name
   #:card-printed_type_line
   #:card-printed_text
   #:card-purchase_uris
   #:card-rarity
   #:card-related_uris
   #:card-reprint
   #:card-scryfall_set_uri
   #:card-set
   #:card-set_name
   #:card-set_search_uri
   #:card-set_uri
   #:card-story_spotlight_number
   #:card-story_spotlight_uri
   #:card-timeshifted
   #:card-tix
   #:card-usd
   #:card-watermark
   #:cards-cards
   #:cards-search
   #:cards-named_exact
   #:cards-named_fuzzy
   #:cards-autocomplete
   #:cards-random
   #:cards-multiverse
   #:cards-mtgo
   #:cards-arena
   #:cards-code_number
   #:cards-id
   #:mtg-set_object
   #:mtg-set_code
   #:mtg-set_mtgo_code
   #:mtg-set_name
   #:mtg-set_set_type
   #:mtg-set_released_at
   #:mtg-set_block_code
   #:mtg-set_block
   #:mtg-set_parent_set_code
   #:mtg-set_card_count
   #:mtg-set_digital
   #:mtg-set_foil_only
   #:mtg-set_icon_svg_uri
   #:mtg-set_scryfall_uri
   #:mtg-set_search_uri
   #:mtg-set_uri
   #:sets-sets
   #:sets-set
   #:ruling-object
   #:ruling-source
   #:ruling-published_at
   #:ruling-comment
   #:rulings-multiverse
   #:rulings-mtgo
   #:rulings-number
   #:rulings-id))
